[build]
    command = "gatsby build"
    publish = "public"
    functions = "functions"
[dev]
    command = "gatsby develop"
    targetPort = 8000
    
[build.environment]
NETLIFY_IMAGE_CDN = "true"

[images]
remote_images = [
  'https://exquisite-ganache-74bc52.netlify.app/.*',
  'https://www.blog.undervalued-x-exchange.co/.*',
  'https://mihovilg1.sg-host.com/.*',
]

[[plugins]]
package = "@netlify/plugin-gatsby"